### ISSUE TITLE
Modify custom icon size

### ISSUE THREAD

**Issue by coderwyd** [unplugin/unplugin-icons#269]
### Describe the bug

When I tried to change the size using font-size I found no change in the icon.

`<i-inline-async style="font-size: 40px" />`

![image](https://user-images.githubusercontent.com/53386850/219602689-28536afd-d711-4a4f-9869-08d82ff23229.png)

### Reproduction

https://github.com/antfu/unplugin-icons/blob/main/examples/vite-vue3/App.vue#L44

### System Info

```Shell
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 5.08 GB / 15.72 GB
  Binaries:
    Node: 16.13.1 - E:\nodejs\node.EXE
    Yarn: 1.22.18 - E:\nodejs\node_global\node_modules\yarn\bin\yarn.CMD
    npm: 8.1.2 - E:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zenonux** [comment]
+1
