### ISSUE TITLE
how to use with other icon lib like xicons ? can you give me a demo

### ISSUE THREAD

**Issue by WormGirl** [unplugin/unplugin-icons#282]
### Clear and concise description of the problem

how to use with other icon lib like xicons ? can you give me a demo

### Suggested solution

this not work
```js
IconsResolver({
          // 自定义icon解析前缀
          prefix: 'icon',
          // 集合名称过长时可以自定义别名
          alias: {
            cus: 'customCommon',
            app: 'customApp',
            ion: '@vicons/ionicons5'
          },
          customCollections: ['@vicons/ionicons5', 'customCommon', 'customApp']
        }),
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Norfeldt** [comment]
I'm also struggling to figure out the use other icons than `<pixelarticons-*icon name*/>` in this https://github.com/antfu/vitesse-webext which uses unplugin-icons. It's really magical how it works.

I wanted to use an icon set like https://icones.netlify.app/collection/fluent-mdl2?s=hide

**Comment by WormGirl** [comment]
> I'm also struggling to figure out the use other icons than `<pixelarticons-*icon name*/>` in this https://github.com/antfu/vitesse-webext which uses unplugin-icons. It's really magical how it works.
> 
> I wanted to use an icon set like https://icones.netlify.app/collection/fluent-mdl2?s=hide

you can install this at https://icon-sets.iconify.design/fluent-mdl2/
```bash
yarn add @iconify-json/fluent-mdl2
```
![image](https://github.com/unplugin/unplugin-icons/assets/16078260/16451f6c-32da-4034-84a0-afbbb2e40e68)
