### ISSUE TITLE
Svelte 4 support

### ISSUE THREAD

**Issue by GauBen** [unplugin/unplugin-icons#295]
### Describe the bug

`types/svelte.d.ts` uses deprecated types. I don't know if this library intends to keep supporting Svelte 3, but the type declaration should now be written like this:

```ts
declare module '~icons/*' {
  import { SvelteComponent } from 'svelte'
  import type { SVGAttributes } from 'svelte/elements'
  export default class extends SvelteComponent<SVGAttributes<EventTarget>> {}
}
```

Here is how it currently looks

![image](https://github.com/antfu/unplugin-icons/assets/48261497/c8821707-8a43-434d-91cc-629c5f30d542)

- `svelte/internal` is not exposed anymore
- `SvelteComponentTyped` is deprecated
- `svelte` does not exist

I can open a merge request with these changes if breaking changes are accepted

### Reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GauBen** [comment]
Slight update to the type declaration:

```ts
declare module '~icons/*' {
  import { SvelteComponent } from 'svelte'
  import type { SvelteHTMLElements } from 'svelte/elements'
  export default class extends SvelteComponent<SvelteHTMLElements['svg']> {}
}
```

Ping @benmccann, sorry to disturb you but I saw you contributed to this repo, you might have some tips to do this the right way

**Comment by userquin** [comment]
@GauBen I've sent this to help in Svelte Discord Server: https://discord.com/channels/457912077277855764/1131342890526851072/1131342890526851072

**Comment by userquin** [comment]
> We're trying to add Svelte 4 support in unplugin-icons, how can we replace the SvelteComponentDev type?
> 
> Svelte 3: 
```ts
// svelte.d.ts => svelte3.d.ts
declare module 'virtual:icons/*' {
  export { SvelteComponentDev as default } from 'svelte/internal'
}

declare module '~icons/*' {
  import { SvelteComponentTyped } from 'svelte'
  export default class extends SvelteComponentTyped<svelte.JSX.IntrinsicElements['svg']> {}
}
```

> I'm using this one for Svelte 4:
```ts
// new svelte.d.ts
declare module 'virtual:icons/*' {
  import { SvelteComponent } from 'svelte'
  import type { SvelteHTMLElements } from 'svelte/elements'
  export default class extends SvelteComponent<SvelteHTMLElements['svg']> {}
}

declare module '~icons/*' {
  import { SvelteComponent } from 'svelte'
  import type { SvelteHTMLElements } from 'svelte/elements'
  export default class extends SvelteComponent<SvelteHTMLElements['svg']> {}
}
```

**Comment by GauBen** [comment]
@leerobert You may use [`yarn patch`](https://yarnpkg.com/cli/patch/) or [`pnpm patch`](https://pnpm.io/cli/patch) to update the type definitions until the new ones are merged
