### ISSUE TITLE
`resolveId` doesn't work as expected when query params contains `.`s

### ISSUE THREAD

**Issue by panchaow** [unplugin/unplugin-icons#322]
### Describe the bug

It's related to the following lines:

https://github.com/unplugin/unplugin-icons/blob/86b820033871a6d47be0060ba6c6e2f925e05261/src/index.ts#L14-L16

extension removal should not be applied on `id` directly.

### Reproduction

try `import IconRss from '~icons/lucide/rss?width=1.25rem&height=1.25rem'`

### System Info

```Shell
System:
    OS: macOS 13.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 71.93 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.1.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Reproduction: https://stackblitz.com/edit/unplugin-unplugin-icons-ih5wso?file=App.vue
