### ISSUE TITLE
Events don't fire in Vue 2

### ISSUE THREAD

**Issue by bmulholland** [unplugin/unplugin-icons#329]
### Describe the bug

At least @click doesn't work

I haven't tried other events but this is certainly enough to dig in.

### Reproduction

https://stackblitz.com/edit/unplugin-unplugin-icons-pcienm?file=src%2FApp.vue

Re-filing https://github.com/unplugin/unplugin-icons/issues/196 with a minimal repro. All I did was take the vue 2 example, add @click on an icon, and wrap the other icon in a div with the same @click.

To see the issue:
1. Open console
2. click the first icon, see that nothing happens
3. click the second icon, with the wrapped div, see that console DOES fire

### System Info

```Shell
https://stackblitz.com/edit/unplugin-unplugin-icons-pcienm?file=src%2FApp.vue
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RayGuo-ergou** [comment]
![image](https://github.com/unplugin/unplugin-icons/assets/33137074/606ab93a-9d55-46eb-a8dd-c1f2ea034fe3)
I don't see any issue here from the repo you provided.

**Comment by bmulholland** [comment]
@RayGuo-ergou which icon did you click on? One of them I wrapped in a div to show that clicks fire on that one. 

I've updated the example to be clear about that: https://stackblitz.com/edit/unplugin-unplugin-icons-pcienm

**Comment by RayGuo-ergou** [comment]
My apologies, did not check the description carefully in that case you can use `@click.native` to fire the event. More information from [vue documentation](https://v2.vuejs.org/v2/guide/components-custom-events#Binding-Native-Events-to-Components)

**Comment by bmulholland** [comment]
Well sure, that's a workaround, but that's not my expectation when I switched to this library. Click worked on the icon element I had before, I'd expect it to work here too.

Anyway, I upgraded to Vue 3 so this doesn't affect me. If you think it's something that isn't worth fixing for others, go ahead and close.
