### ISSUE TITLE
How to auto import icon set with plural names?

### ISSUE THREAD

**Issue by nova1751** [unplugin/unplugin-icons#335]
### Describe the bug

I'm very confused about how to auto-import icons like the picture below,I tried the forms like `<i-gravity-ui-cloud-gear />` and `<i-GravityUI-cloud-gear />` but it didn't work.
<img width="729" alt="Snipaste_2023-12-17_21-25-19" src="https://github.com/unplugin/unplugin-icons/assets/97817985/c602327e-4ee3-4ca4-8c86-d576428fd7b1">
<img width="399" alt="Snipaste_2023-12-17_21-30-58" src="https://github.com/unplugin/unplugin-icons/assets/97817985/c1483b4a-d47d-4a36-b3eb-786730123f4c">

### Reproduction

1

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 1.90 GB / 15.71 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Use `:` to separate collection and icon: `<i-gravity-ui:cloud-gear />`

https://github.com/unplugin/unplugin-icons/pull/316

**Comment by nova1751** [comment]
> Use `:` to separate collection and icon: `<i-gravity-ui:cloud-gear />`
> 
> #316

It doesn't seem to work though,it still doesn't render correctly.
<img width="342" alt="Snipaste_2023-12-17_21-48-23" src="https://github.com/unplugin/unplugin-icons/assets/97817985/5f306259-6efa-4c14-8686-42ed64192491">

**Comment by userquin** [comment]
what fw are you using?

**Comment by nova1751** [comment]
> what fw are you using?

```
    "vite": "^4.4.9",
    "vue": "^3.3.12",
```

**Comment by userquin** [comment]
@nova1751 it seems `gravity-ui` collection missing (shoulld be very new), add it to resolver options via ` enabledCollections: ['gravity-ui'],`  to `IconResolver`: https://stackblitz.com/edit/unplugin-unplugin-icons-rupzop?file=vite.config.ts,App.vue

**Comment by userquin** [comment]
Next time check [examples readme page](https://github.com/unplugin/unplugin-icons/tree/main/examples) to provide a playground.

**Comment by nova1751** [comment]
> Next time check [examples readme page](https://github.com/unplugin/unplugin-icons/tree/main/examples) to provide a playground.

Oh, I see.Thanks for your help.
