### ISSUE TITLE
An issue for vue2(<2.7) compiler with "transpile is not a function"

### ISSUE THREAD

**Issue by twt898xu** [unplugin/unplugin-icons#355]
### Describe the bug

when I use the latest version (0.18.5) with my vue2 product, it doesn't work
it will throw a "transpile is not a function" error
I found a problem in the code

this code on `src/core/compilers/vue2.ts` file
```
const transpile = (await importModule('vue-template-es2015-compiler'))
    .default
```

I think we don't need the `.default`. because the `importModule` method has parsed it

### Reproduction

https://stackblitz.com/edit/unplugin-unplugin-icons-3xjrzc?file=main.ts

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 77.65 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    bun: 0.8.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.123
    Edge: 123.0.2420.81
    Safari: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wjw020206** [comment]
I also encountered this problem. Is there any good solution at this stage?

**Comment by twt898xu** [comment]
@wjw020206  you can downgrade to v0.17.0

**Comment by wjw020206** [comment]
> @wjw020206 you can downgrade to v0.17.0

alright, thank you very much

**Comment by wjw020206** [comment]
> @wjw020206 you can downgrade to v0.17.0

 hi. tried to use v0.17.0 but there were new problems, Prompt error: Typerror: Require (...). Default is not a function

**Comment by twt898xu** [comment]
you can remove the `default()` and try again

**Comment by wjw020206** [comment]
> you can remove the `default()` and try again

I tried it, the problem changed
```js
module.exports = function unplugin() {
  return [
    require('unplugin-auto-import/webpack').default({
      imports: ['vue', 'vue-router', 'pinia'],
      eslintrc: {
        enabled: true
      },
      dts: 'src/typings/auto-imports.d.ts'
    }),
    require('unplugin-vue-components/webpack').default({
      dts: 'src/typings/components.d.ts',
      resolvers: [require('unplugin-icons/resolver')]
    }),
    require('unplugin-icons/webpack').default({ // The error appears in this line
      compiler: 'vue2',
      scale: 1,
      defaultClass: 'inline-block',
      autoInstall: true
    })
  ];
};
```

**Comment by twt898xu** [comment]
same as above, you don't need the `default()`

like
```javascript
module.exports = function unplugin() {
  return [
    require('unplugin-auto-import/webpack').default({
      imports: ['vue', 'vue-router', 'pinia'],
      eslintrc: {
        enabled: true
      },
      dts: 'src/typings/auto-imports.d.ts'
    }),
    require('unplugin-vue-components/webpack').default({
      dts: 'src/typings/components.d.ts',
      resolvers: [require('unplugin-icons/resolver')()]
    }),
    require('unplugin-icons/webpack')({ // The error appears in this line
      compiler: 'vue2',
      scale: 1,
      defaultClass: 'inline-block',
      autoInstall: true
    })
  ];
};
```

**Comment by wjw020206** [comment]
> same as above, you don't need the `default()`
> 
> like
> 
> ```js
> module.exports = function unplugin() {
>   return [
>     require('unplugin-auto-import/webpack').default({
>       imports: ['vue', 'vue-router', 'pinia'],
>       eslintrc: {
>         enabled: true
>       },
>       dts: 'src/typings/auto-imports.d.ts'
>     }),
>     require('unplugin-vue-components/webpack').default({
>       dts: 'src/typings/components.d.ts',
>       resolvers: [require('unplugin-icons/resolver')()]
>     }),
>     require('unplugin-icons/webpack')({ // The error appears in this line
>       compiler: 'vue2',
>       scale: 1,
>       defaultClass: 'inline-block',
>       autoInstall: true
>     })
>   ];
> };
> ```

Thank you very much, I will change it as follows.
```js
module.exports = function unplugin() {
  return [
    require('unplugin-auto-import/webpack').default({
      imports: ['vue', 'vue-router', 'pinia'],
      eslintrc: {
        enabled: true
      },
      dts: 'src/typings/auto-imports.d.ts'
    }),
    require('unplugin-vue-components/webpack').default({
      dts: 'src/typings/components.d.ts',
      resolvers: [require('unplugin-icons/resolver')()]
    }),
    require('unplugin-icons/webpack')({
      compiler: 'vue2',
      scale: 1,
      defaultClass: 'inline-block',
      autoInstall: true
    })
  ];
};
```
