### ISSUE TITLE
SvelteKit Library import error

### ISSUE THREAD

**Issue by vdawg-git** [unplugin/unplugin-icons#378]
### Describe the bug

It fails to resolve unplugin icons in a component imported from a UI library/dependency.
Edit: This is during `dev` and `build`.

```js
✘ [ERROR] Could not resolve "virtual:icons/mingcute/close-line"

    ../../node_modules/.pnpm/@..@0.0.1-rc.32_@types+node@22.7.0_@vue+compiler-sfc@3.5.8_jiti@1.21.6_postcss-load-_hbmxqbqxr2ktizjeyao532r5he/node_modules/@../ui/dist/Notification/Notification.svelte:42:22:
      42 │ import IconClose from "virtual:icons/mingcute/close-line";
         ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "virtual:icons/mingcute/close-line" as external to exclude it from the
  bundle, which will remove this error and leave the unresolved path in the bundle.
``` 

### Reproduction

Consumer:
https://github.com/vdawg-git/unplugin-icon-issue-consumer

Minimal library repo:
https://github.com/vdawg-git/unplugin-icons-issue

### System Info

```Shell
  System:
    OS: Linux 6.10 EndeavourOS
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 13.95 GB / 31.07 GB
    Container: Yes
    Shell: 3.7.1 - /bin/fish
  Binaries:
    Node: 22.9.0 - /usr/bin/node
    npm: 10.8.3 - /usr/bin/npm
    pnpm: 9.11.0 - /usr/bin/pnpm
    bun: 1.1.29 - /usr/bin/bun
  Browsers:
    Brave Browser: 129.1.70.117
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vdawg-git** [comment]
Hey, thank you for the quick reply.

I added them now, however the errors occurs during `dev`/`build` and is not a type error.
So the error still occurs

**Comment by userquin** [comment]
So, the problem is about importing a component from another library, I'm checking what's the problem and solution

**Comment by vdawg-git** [comment]
Hmm, I see. Do you know of a way to do the alternatives? 
Are there plugins for this? unplugin-icons is so nice and I dont want to drop it :D

**Comment by userquin** [comment]
Maybe you should check [UnoCSS Preset Icons](https://unocss.dev/presets/icons)

**Comment by vdawg-git** [comment]
Awesome, thank you for sharing! 
I will check everything out :)

**Comment by vdawg-git** [comment]
The quest continues: https://github.com/unocss/unocss/issues/4166 
But I am making progress
