### ISSUE TITLE
Error while loading some icons : `Property "idMap" was accessed during render but is not defined on instance.`

### ISSUE THREAD

**Issue by EDM115** [unplugin/unplugin-icons#385]
### Describe the bug

Some icons load without any issue (check the `works.vue` file) but for some odd reason some others don't (check the `not-works.vue` file)

Errors :  
```
[Vue warn]: Property "idMap" was accessed during render but is not defined on instance. 
  at <VscodeIconsFileTypePython> 
  at <VComponentIcon tag="i" icon= {name: 'vscode-icons-file-type-python', __v_skip: true, render: ƒ, data: ƒ} class="v-icon notranslate v-theme--dark v-icon--size-default"  ... > 
  at <VIcon icon= {name: 'vscode-icons-file-type-python', __v_skip: true, render: ƒ, data: ƒ} > 
  at <NotWorks> 
  at <App>

[Vue warn]: Unhandled error during execution of render function 
  at <VscodeIconsFileTypePython> 
  at <VComponentIcon tag="i" icon= {name: 'vscode-icons-file-type-python', __v_skip: true, render: ƒ, data: ƒ} class="v-icon notranslate v-theme--dark v-icon--size-default"  ... > 
  at <VIcon icon= {name: 'vscode-icons-file-type-python', __v_skip: true, render: ƒ, data: ƒ} > 
  at <NotWorks> 
  at <App>

App.vue:26 [Vue warn]: Unhandled error during execution of component update 
  at <App>

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'vscodeIconsFileTypePython0')
    at Proxy.render (file-type-python:18:23)
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ati5bg?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: Windows 11 10.0.22635
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 3.00 GB / 13.85 GB
  Binaries:
    Node: 22.8.0 - ~\AppData\Local\fnm_multishells\14252_1730292168674\node.EXE
    npm: 10.9.0 - ~\AppData\Local\fnm_multishells\14252_1730292168674\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\Microsoft\WinGet\Links\pnpm.EXE
    bun: 1.1.34 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.8)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Found the problem (check the linked PR), in the meantime remove `features: { optionsAPI: false },` from the Vite Vue plugin.

**Comment by EDM115** [comment]
you're really the goat man 🫶
